steps:  
  - name: Download Clang  
   run: |  
    wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-release/clang-r443413c.tar.gz -O aosp-clang.tar.gz  
  
  - name: Build Kernel  
   uses: dabao1955/kernel_build_action@main  
   with:  
    kernel-url: https://github.com/Svirusx/Nethunter-Kernel-S20_FE_5G.git  
    kernel-branch: nethunter-13.0  
    config: wirus_defconfig  
    arch: arm64  
    aosp-gcc: true  
    aosp-clang: true  
    clang-path: /opt/clang  
    android-version: 12  
    disable-lto: true
